### ISSUE TITLE
希望能尽快编写手册的主体部分

### ISSUE THREAD

**Issue by xkwxdyy** [qinglee/wrapstuff#1]
我 clone 了 5b4b1a36b3ee51684d035934b9b3f1547174e671 这个推送下的仓库，并且有以下的 MWE
```latex
\documentclass{ctexart}
\usepackage{wrapstuff}
\usepackage{graphicx}

\begin{document}

\begin{wrapstuff}
  如彭奇和瓦特曼的公共事业所证实的那样有一个胡子雪雪白的上帝超
  越时间超越空间确确实实存在他在神圣的冷漠神圣的疯狂神圣的喑哑的高处深
  深地爱着我们除了少数的例外不知什么原因但时间将会揭示他像神圣的密兰达
  一样和人们一起忍受着痛苦这班人不知什么原因但时间将会揭示生活在痛苦中
  生活在烈火中这烈火这火焰如果继续燃烧毫无疑问将使穹苍着火也就是说将地
  狱炸上天去天是那么蓝那么澄澈那么平静这种平静尽管时断时续总比没有好得
  多但是别这么快还要进一步考虑到泰斯丢和丘那德的人体测定学院的未完成的
  研究结果早已断定毫无疑问换句话说除了依附着人类的疑问之外别无其他疑问
  根据泰斯丢和丘那德的未完成的劳动的结果早已作出如下的论断但是别这么快
\includegraphics[width = 4cm]{example-image.pdf}
\end{wrapstuff}

\end{document}
```

但是得到的是
![image](https://user-images.githubusercontent.com/87134063/178309225-fc0a7472-e115-44f0-b3d7-1186b83993f4.png)

而没有文字部分。我猜这个大概率是我使用方式不当，但是我
```bash
xelatex wrapstuff.dtx
```
得到的手册里没有使用方式和细节的说明，希望能够尽快地编写手册的主体部分～或者如果能在此简要说明 `wrapstuff` 环境的基本使用方式就最好不过了，非常感谢。很期待这个宏包。

**Comment by qinglee** [comment]
简单例子如下：
```LaTeX
\documentclass{ctexart}
\usepackage{wrapstuff}
\usepackage{zhlipsum}
\usepackage{graphicx}

\begin{document}

\begin{wrapstuff}
\includegraphics[width = 4cm]{example-image-a.pdf}
\end{wrapstuff}

\zhlipsum[1][name=zhufu]

\begin{wrapstuff}[top=5, ratio=2/5, column=false]
\includegraphics[width = 4cm]{example-image-b.pdf}
\end{wrapstuff}

\zhlipsum[2][name=zhufu]

\begin{wrapstuff}[top=0,ratio=1]
\includegraphics[width = 4cm]{example-image-c.pdf}
\end{wrapstuff}

\zhlipsum[3][name=zhufu]

\begin{wrapstuff}[top=1,ratio=0]
\includegraphics[width = 4cm]{example-image-a.pdf}
\end{wrapstuff}

\zhlipsum[4-8][name=zhufu]

\begin{wrapstuff}[top=3,ratio=1,voffset=-8pt]
\includegraphics[width = 4cm]{example-image-b.pdf}
\end{wrapstuff}

\zhlipsum[9-12][name=zhufu]

\end{document}
```
使用了 LaTeX 的 `para/begin` 和 `para/end` 钩子，只需要把待绕排的内容放在 `wrapstuff` 环境里就可以，会在环境之后的段落开始绕排。

* `top` 选项控制在段落的第几行之后开始绕排，可以设置为非负值
* `ratio` 选项控制绕排左侧的正文行宽的比例，可以设置为 `[0,1]` 中的合理数字
* `column` 选项控制是否将两侧的文字分栏显示
* `voffset` 用于调整绕排内容的竖直位置

目前的实现有一些限制。比较明显的问题是，由于使用 `\parshape` 在段落中挖空放入绕排内容，因此与 LaTeX 的列表环境不兼容。这个问题应该可以解决，但我还没想好怎么做合适。

**Comment by qinglee** [comment]
> 太感谢了，效果很惊艳！期待您能解决列表问题，这个解决后会极大地解决 [exam-zh](https://gitee.com/zepinglee/exam-zh) 的图文排版的板块。

列表兼容问题已经在 https://github.com/qinglee/wrapstuff/commit/ca39a4641dd58330ae1662d663c335970863bbbd 解决了。

**Comment by xkwxdyy** [comment]
86cd68b55770ce91b30703278171351701bda95a 中先使用 `tex wrapstuff.dtx` 编译出 `sty` 文件后使用 `latexmk -xelatex wrapstuff.dtx` 出现报错
```bash
! Undefined control sequence.
l.150 \SideBySideExampleSet
                            { numbers = none }
? 
```
强制编译后并没有 PDF 生成。

**Comment by qinglee** [comment]
@xkwxdyy 先更新 ctex 包，`\SideBySideExampleSet` 在前几天发布的 ctxdoc 中才有定义。

另外，编译文档最方便的应该是运行 `l3build doc`。

**Comment by xkwxdyy** [comment]
> @xkwxdyy 先更新 ctex 包，`\SideBySideExampleSet` 在前几天发布的 ctxdoc 中才有定义。
> 
> 另外，编译文档最方便的应该是运行 `l3build doc`。

非常感谢，已经成功编译了。
