### ISSUE TITLE
Doc in english

### ISSUE THREAD

**Issue by cpierquet** [qinglee/wrapstuff#4]
Tks for the useful package, is it possible to provide the doc in english too ?

Ced'

**Comment by qinglee** [comment]
English is not my native language and I don't have any plans to supplement the English documentation, sorry about that.

**Comment by jasperhabicht** [comment]
I could help translating it. I think my Chinese is good enough to understand the manual.

**Comment by qinglee** [comment]
I think the user manual part is stable, many thanks to @jasperhabicht.
