### ISSUE TITLE
the latest release only includes a dtx

### ISSUE THREAD

**Issue by vale981** [qinglee/wrapstuff#9]
Hi, 

Thank you for making this nice package :).

Could you include an sty file in the CTAN/GitHub release?

Cheers,
Valentin

**Comment by qinglee** [comment]
Your can get the .sty file after running `tex wrapstuff.dtx`.

**Comment by vale981** [comment]
but some tex installations may lack the packages to do that, but nvm :]

Thanks for the reply.
